
  - package:
       name: "haproxy"
       state: present 
 
  - template:
         src: haproxy.cfg.j2
         dest: "/etc/haproxy/haproxy.cfg"
    register: status

  - service:
         name: "haproxy"
         state: restarted
    when: status.changed == true


